services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
