services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:3000"
