services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
